/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Tutor_rootRouteImport } from './routes/tutor/__root'
import { Route as TutorsRouteImport } from './routes/tutors'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterTutorRouteImport } from './routes/register-tutor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorsIdRouteImport } from './routes/tutors.$id'
import { Route as TutorStudentsRouteImport } from './routes/tutor/students'
import { Route as TutorSettingsRouteImport } from './routes/tutor/settings'
import { Route as TutorScheduleRouteImport } from './routes/tutor/schedule'
import { Route as TutorMessagesRouteImport } from './routes/tutor/messages'
import { Route as TutorEarningsRouteImport } from './routes/tutor/earnings'
import { Route as TutorDashboardRouteImport } from './routes/tutor/dashboard'
import { Route as TutorAnalyticsRouteImport } from './routes/tutor/analytics'
import { Route as DashboardTutorRouteImport } from './routes/dashboard.tutor'
import { Route as DashboardStudentRouteImport } from './routes/dashboard.student'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'

const Tutor_rootRoute = Tutor_rootRouteImport.update({
  id: '/tutor/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorsRoute = TutorsRouteImport.update({
  id: '/tutors',
  path: '/tutors',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterTutorRoute = RegisterTutorRouteImport.update({
  id: '/register-tutor',
  path: '/register-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorsIdRoute = TutorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TutorsRoute,
} as any)
const TutorStudentsRoute = TutorStudentsRouteImport.update({
  id: '/tutor/students',
  path: '/tutor/students',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorSettingsRoute = TutorSettingsRouteImport.update({
  id: '/tutor/settings',
  path: '/tutor/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorScheduleRoute = TutorScheduleRouteImport.update({
  id: '/tutor/schedule',
  path: '/tutor/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorMessagesRoute = TutorMessagesRouteImport.update({
  id: '/tutor/messages',
  path: '/tutor/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorEarningsRoute = TutorEarningsRouteImport.update({
  id: '/tutor/earnings',
  path: '/tutor/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorDashboardRoute = TutorDashboardRouteImport.update({
  id: '/tutor/dashboard',
  path: '/tutor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorAnalyticsRoute = TutorAnalyticsRouteImport.update({
  id: '/tutor/analytics',
  path: '/tutor/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTutorRoute = DashboardTutorRouteImport.update({
  id: '/dashboard/tutor',
  path: '/dashboard/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/dashboard/student',
  path: '/dashboard/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/register-tutor': typeof RegisterTutorRoute
  '/settings': typeof SettingsRoute
  '/tutors': typeof TutorsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/tutor': typeof DashboardTutorRoute
  '/tutor': typeof Tutor_rootRoute
  '/tutor/analytics': typeof TutorAnalyticsRoute
  '/tutor/dashboard': typeof TutorDashboardRoute
  '/tutor/earnings': typeof TutorEarningsRoute
  '/tutor/messages': typeof TutorMessagesRoute
  '/tutor/schedule': typeof TutorScheduleRoute
  '/tutor/settings': typeof TutorSettingsRoute
  '/tutor/students': typeof TutorStudentsRoute
  '/tutors/$id': typeof TutorsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/register-tutor': typeof RegisterTutorRoute
  '/settings': typeof SettingsRoute
  '/tutors': typeof TutorsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/tutor': typeof DashboardTutorRoute
  '/tutor': typeof Tutor_rootRoute
  '/tutor/analytics': typeof TutorAnalyticsRoute
  '/tutor/dashboard': typeof TutorDashboardRoute
  '/tutor/earnings': typeof TutorEarningsRoute
  '/tutor/messages': typeof TutorMessagesRoute
  '/tutor/schedule': typeof TutorScheduleRoute
  '/tutor/settings': typeof TutorSettingsRoute
  '/tutor/students': typeof TutorStudentsRoute
  '/tutors/$id': typeof TutorsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/register-tutor': typeof RegisterTutorRoute
  '/settings': typeof SettingsRoute
  '/tutors': typeof TutorsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/tutor': typeof DashboardTutorRoute
  '/tutor/__root': typeof Tutor_rootRoute
  '/tutor/analytics': typeof TutorAnalyticsRoute
  '/tutor/dashboard': typeof TutorDashboardRoute
  '/tutor/earnings': typeof TutorEarningsRoute
  '/tutor/messages': typeof TutorMessagesRoute
  '/tutor/schedule': typeof TutorScheduleRoute
  '/tutor/settings': typeof TutorSettingsRoute
  '/tutor/students': typeof TutorStudentsRoute
  '/tutors/$id': typeof TutorsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/register-tutor'
    | '/settings'
    | '/tutors'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/student'
    | '/dashboard/tutor'
    | '/tutor'
    | '/tutor/analytics'
    | '/tutor/dashboard'
    | '/tutor/earnings'
    | '/tutor/messages'
    | '/tutor/schedule'
    | '/tutor/settings'
    | '/tutor/students'
    | '/tutors/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/register-tutor'
    | '/settings'
    | '/tutors'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/student'
    | '/dashboard/tutor'
    | '/tutor'
    | '/tutor/analytics'
    | '/tutor/dashboard'
    | '/tutor/earnings'
    | '/tutor/messages'
    | '/tutor/schedule'
    | '/tutor/settings'
    | '/tutor/students'
    | '/tutors/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/register-tutor'
    | '/settings'
    | '/tutors'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/student'
    | '/dashboard/tutor'
    | '/tutor/__root'
    | '/tutor/analytics'
    | '/tutor/dashboard'
    | '/tutor/earnings'
    | '/tutor/messages'
    | '/tutor/schedule'
    | '/tutor/settings'
    | '/tutor/students'
    | '/tutors/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRouteWithChildren
  RegisterTutorRoute: typeof RegisterTutorRoute
  SettingsRoute: typeof SettingsRoute
  TutorsRoute: typeof TutorsRouteWithChildren
  DashboardStudentRoute: typeof DashboardStudentRoute
  DashboardTutorRoute: typeof DashboardTutorRoute
  Tutor_rootRoute: typeof Tutor_rootRoute
  TutorAnalyticsRoute: typeof TutorAnalyticsRoute
  TutorDashboardRoute: typeof TutorDashboardRoute
  TutorEarningsRoute: typeof TutorEarningsRoute
  TutorMessagesRoute: typeof TutorMessagesRoute
  TutorScheduleRoute: typeof TutorScheduleRoute
  TutorSettingsRoute: typeof TutorSettingsRoute
  TutorStudentsRoute: typeof TutorStudentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor/__root': {
      id: '/tutor/__root'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof Tutor_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutors': {
      id: '/tutors'
      path: '/tutors'
      fullPath: '/tutors'
      preLoaderRoute: typeof TutorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-tutor': {
      id: '/register-tutor'
      path: '/register-tutor'
      fullPath: '/register-tutor'
      preLoaderRoute: typeof RegisterTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutors/$id': {
      id: '/tutors/$id'
      path: '/$id'
      fullPath: '/tutors/$id'
      preLoaderRoute: typeof TutorsIdRouteImport
      parentRoute: typeof TutorsRoute
    }
    '/tutor/students': {
      id: '/tutor/students'
      path: '/tutor/students'
      fullPath: '/tutor/students'
      preLoaderRoute: typeof TutorStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/settings': {
      id: '/tutor/settings'
      path: '/tutor/settings'
      fullPath: '/tutor/settings'
      preLoaderRoute: typeof TutorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/schedule': {
      id: '/tutor/schedule'
      path: '/tutor/schedule'
      fullPath: '/tutor/schedule'
      preLoaderRoute: typeof TutorScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/messages': {
      id: '/tutor/messages'
      path: '/tutor/messages'
      fullPath: '/tutor/messages'
      preLoaderRoute: typeof TutorMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/earnings': {
      id: '/tutor/earnings'
      path: '/tutor/earnings'
      fullPath: '/tutor/earnings'
      preLoaderRoute: typeof TutorEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/dashboard': {
      id: '/tutor/dashboard'
      path: '/tutor/dashboard'
      fullPath: '/tutor/dashboard'
      preLoaderRoute: typeof TutorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/analytics': {
      id: '/tutor/analytics'
      path: '/tutor/analytics'
      fullPath: '/tutor/analytics'
      preLoaderRoute: typeof TutorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tutor': {
      id: '/dashboard/tutor'
      path: '/dashboard/tutor'
      fullPath: '/dashboard/tutor'
      preLoaderRoute: typeof DashboardTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface TutorsRouteChildren {
  TutorsIdRoute: typeof TutorsIdRoute
}

const TutorsRouteChildren: TutorsRouteChildren = {
  TutorsIdRoute: TutorsIdRoute,
}

const TutorsRouteWithChildren =
  TutorsRoute._addFileChildren(TutorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRouteWithChildren,
  RegisterTutorRoute: RegisterTutorRoute,
  SettingsRoute: SettingsRoute,
  TutorsRoute: TutorsRouteWithChildren,
  DashboardStudentRoute: DashboardStudentRoute,
  DashboardTutorRoute: DashboardTutorRoute,
  Tutor_rootRoute: Tutor_rootRoute,
  TutorAnalyticsRoute: TutorAnalyticsRoute,
  TutorDashboardRoute: TutorDashboardRoute,
  TutorEarningsRoute: TutorEarningsRoute,
  TutorMessagesRoute: TutorMessagesRoute,
  TutorScheduleRoute: TutorScheduleRoute,
  TutorSettingsRoute: TutorSettingsRoute,
  TutorStudentsRoute: TutorStudentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
